REPOSITORY := erwinnttdata
NAME := wp_muellerpublic_data
VERSION ?= 1.0-build_001

build: _build ##@targets Builds the docker image.

deploy: _deploy ##@targets Deployes the docker image to the repository.

include ../make_utils/Makefile.help
include ../make_utils/Makefile.functions
include ../make_utils/Makefile.image
