REPOSITORY := erwinnttdata
NAME := maradns
VERSION ?= 2.0.13-build_008

build: _build ##@target Builds the docker image.

deploy: _deploy ##@target Deployes the docker image to the repository.

include ../../make_utils/Makefile.help
include ../../make_utils/Makefile.functions
include ../../make_utils/Makefile.image
