REPOSITORY := erwinnttdata
NAME := maradns
VERSION ?= 2.0.13-build_011

build: _build ##@targets Builds the docker image.

deploy: _deploy ##@targets Deployes the docker image to the repository.

include ../../make_utils/Makefile.help
include ../../make_utils/Makefile.functions
include ../../make_utils/Makefile.image
