REPOSITORY := erwinnttdata
NAME := wordpress
VERSION ?= 4.5-fpm-build_002

build: _build ##@targets Builds the docker image.

clean: _clean ##@targets Removes the local docker image.

deploy: _deploy ##@targets Deployes the docker image to the repository.

include ../make_utils/Makefile.help
include ../make_utils/Makefile.functions
include ../make_utils/Makefile.image
