REPOSITORY := erwinnttdata
NAME := mysql
VERSION ?= 5.7-build_009

build: _build ##@target Builds the docker image.

deploy: _deploy ##@target Deployes the docker image to the repository.

include ../make_utils/Makefile.help
include ../make_utils/Makefile.functions
include ../make_utils/Makefile.image
